# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Things that make my head hurt
email: nic@nicholasjackson.io
description: Nic Jacksons coding and code related blog
baseurl: '' # the subpath of your site, e.g. /blog
url: 'https://nicholasjackson.io' # the base hostname & protocol for your site
twitter_username: sheriffjackson
github_username: nicholasjackson

# Build settings
markdown: kramdown
permalink: pretty
include:
  - _pages
exclude:
  - Gemfile
  - Gemfile.lock
gems:
  - jekyll-paginate
  - jekyll/tagging
  - jekyll-sitemap

# Pagination
paginate: 12

# Tags
tag_page_layout: tag_page
tag_page_dir: tag
tag_permalink_style: pretty

authors:
  nic:
    name: Nic Jackson
    display_name: Nic Jackson
    bio: Author, Geek, Ultrarunner and in my spare time developer advocate at HashiCorp.  Currently writing Building Microservices in Go to be published by Packt 2017 https://goo.gl/vUKtPT. Maintainer of Minke https://minke.rocks, build and test tool for microservices.
    gravatar: https://s.gravatar.com/avatar/05d3d38fb637ed5240b637f57394d587?s=80
    email: jackson.nic@gmail.com
    web: https://nicholasjackson.io
    twitter: sheriffjackson
    github: nicholasjackson
