# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Things that make my head hurt
email: nic@nicholasjackson.io
description: Nic Jacksons coding and code related blog
baseurl: '' # the subpath of your site, e.g. /blog
url: 'https://nicholasjackson.io' # the base hostname & protocol for your site
twitter_username: sheriffjackson
github_username: nicholasjackson

# Build settings
markdown: kramdown
permalink: pretty
include:
  - _pages
  - _tag
exclude:
  - Gemfile
  - Gemfile.lock
gems:
  - jekyll-paginate
  - jekyll-sitemap

# Pagination
paginate: 12

authors:
  nic:
    name: Nic Jackson
    display_name: Nic Jackson
    bio: Author, Geek, Ultrarunner and in my spare time developer advocate at HashiCorp.  Author of <a href="https://goo.gl/vUKtPT">Building Microservices in Go</a>. Maintainer of Minke https://minke.rocks, build and test tool for microservices.
    gravatar: https://s.gravatar.com/avatar/05d3d38fb637ed5240b637f57394d587?s=80
    email: jackson.nic@gmail.com
    web: https://nicholasjackson.io
    twitter: sheriffjackson
    github: nicholasjackson
