# Site wide configuration

title:            Things that make my head hurt
locale:           en_US
#url: http://nicholasjackson.github.io
#url: http://0.0.0.0:4000
# Jekyll configuration

permalink:   /:categories/:title/

sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

encoding: utf-8
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false


# Site owner
owner:
  name: Nic Jackson
  avatar: bio-photo.jpg
  bio: "Geek, Ultrarunner and in my spare time software engineering evangelist for notonthehighstreet.com."
  email:
  disqus-shortname: thingsthatmakemyheadhurt
  twitter: sheriffjackson
  facebook:
  google:
    plus: NicJackson
    analytics: UA-53659420-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  google_plus: NicJackson
  github: nicholasjackson
  stackoverflow:
  linkedin: jacksonnic
  instagram:
  lastfm:
  tumblr:
  pinterest:
  foursquare:
  steam:
  dribbble:

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
