# Site wide configuration

title:            Things that make my head hurt
locale:           en_US
url: http://0.0.0.0:4000

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Nic Jackson
  avatar: bio-photo.jpg
  bio: "Geek, Ultrarunner and part time software engineering manager for Marks and Spencer."
  email:
  disqus-shortname: thingsthatmakemyheadhurt
  twitter:
  facebook:
  google:
    plus: NicJackson
    analytics: UA-53659420-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  google_plus: NicJackson
  github: nicholasjackson
  stackoverflow:
  linkedin: jacksonnic
  instagram:
  lastfm:
  tumblr:
  pinterest:
  foursquare:
  steam:
  dribbble:

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
